spring:
  # thymleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000

# Mybatis-plus配置
mybatis-plus:
  # 配置Maperr.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.taozi.seckill.pojo

# Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.taozi.seckill.mapper: debug